.classpath, .gitignore, .project, .settings/org.eclipse.jdt.core.prefs, .settings/org.eclipse.m2e.core.prefs, README.md, pom.xml, src/main/java/com/axonivy/github/GitHubRepoManager.java
- delete branch after merge
- disable wiki, disable projects, disable issues
- remove all hooks
- branch protection rules for master, release/8.0, release/7.0 etc.
using patterns over API not possible, yet.
=> XIVY-8512 Configure GitHub repos as we like

build/raise-web-tester-version/Jenkinsfile, build/raise-web-tester-version/raise.sh
- Allow set snapshot version
- Add more repos to update
=> Improve raise webtester

build/scan-issues/Jenkinsfile, github-repo-manager/pom.xml, github-repo-manager/src/main/java/com/axonivy/github/GitHubIssueScanner.java, github-repo-manager/src/main/java/com/axonivy/github/scan/Issue.java, github-repo-manager/src/main/java/com/axonivy/github/scan/ScanIssueReporter.java, github-repo-manager/src/main/release-notes/release-notes.txt
Issue Scanning now compares the list of issues found in the logs and those reported to be fixed in the release notes (JIRA).
=> XIVY-11120 Issue Scanning now shows with issues are missing in log or RN

build/raise-deps/Jenkinsfile, build/raise-version/Jenkinsfile, build/raise-version/raise.sh
- raise-deps.sh
- Fix pipelines
=> raise deps

build/Dockerfile
=> Add ssh to fix build

github-repo-manager/src/main/java/com/axonivy/github/GitHubStaleBranchesDetector.java
- Enable issues for market repos
- Slighlty improve stale branches detector
=> market repos

build/raise-version/raise.sh
This fixes raise-deps on vscode-extensions
=> Add config-editor-client to raise-version

build/raise-build-plugin-version/Jenkinsfile, build/raise-build-plugin-version/raise.sh, build/raise-deps/Jenkinsfile, build/raise-deps/raise.sh, build/raise-ivy-projects-version/Jenkinsfile, build/raise-ivy-projects-version/raise.sh, build/raise-portal-version/Jenkinsfile, build/raise-portal-version/raise.sh, build/raise-version/Jenkinsfile, build/raise-version/raise.sh, build/raise-web-tester-version/Jenkinsfile, build/raise-web-tester-version/raise.sh, build/raiseRepo.sh, build/release-branch/Jenkinsfile
- Remove dryRun parameter from the raise scripts
- Evaluate DRY_RUN only on the raisRepo.sh
=> Use environment varialbe for DRY_RUN

build/raise-build-plugin-version/Jenkinsfile, build/raise-build-plugin-version/raise.sh, build/raise-deps/Jenkinsfile, build/raise-deps/raise.sh, build/raise-ivy-projects-version/Jenkinsfile, build/raise-ivy-projects-version/raise.sh, build/raise-portal-version/Jenkinsfile, build/raise-portal-version/raise.sh, build/raise-version/Jenkinsfile, build/raise-version/raise.sh, build/raise-web-tester-version/Jenkinsfile, build/raise-web-tester-version/raise.sh, build/raiseRepo.sh
Use the environment variable 'GITHUB_TOKEN_FILE'
If env variable GITHUB_TOKEN_FILE is not set:
- Only check if github cli is authenticated
- This is usefull if used localy where the gh cli is authenticated anyway
=> Use environment variable for github token file

build/raise-build-plugin-version/raise.sh, build/raise-deps/raise.sh, build/raise-ivy-projects-version/raise.sh, build/raise-portal-version/raise.sh, build/raise-version/raise.sh, build/raise-web-tester-version/raise.sh, build/raiseRepo.sh
Do skip the repo if there is no change
=> Generalize git commit in the reaiseRepo.sh

github-repo-manager/src/main/java/com/axonivy/github/file/GitHubMissingFilesDetector.java
@nqhoan-axonivy  Upps I broke it
=> Fix previous commit that addMissingFile is called again

github-repo-manager/src/main/java/com/axonivy/github/file/FileReference.java, github-repo-manager/src/main/java/com/axonivy/github/file/GitHubFiles.java, github-repo-manager/src/main/java/com/axonivy/github/file/GitHubFilesDetector.java, github-repo-manager/src/main/java/com/axonivy/github/file/GitHubMissingFiles.java, github-repo-manager/src/main/java/com/axonivy/github/file/GitHubMissingFilesDetector.java, github-repo-manager/src/main/java/com/axonivy/github/file/Logger.java
refactoring only ... to make removal simpler in sub-sequent pr
=> refactor: simplify logic ... separate file-load and logs

build/raiseRepo.sh
- brakes mvn-tycho build running on it in ivy-core.
=> fix: no colon (:) in dir-name

github-repo-manager/src/main/java/com/axonivy/github/GitHubRepoTagger.java, github-repo-manager/src/main/java/com/axonivy/github/GitHubRepos.java
Add the project-build-plugin to the repos that are scanned for issues. However do not add it to the repos that are tagged or branched.
=> Scan issues in project-build-plugin

github-repo-manager/src/main/java/com/axonivy/github/file/GitHubFiles.java, github-repo-manager/src/main/java/com/axonivy/github/file/GitHubMissingFiles.java, github-repo-manager/src/main/resources/com/axonivy/github/file/CODE_OF_CONDUCT.md
the new coc: https://1ivy.atlassian.net/browse/MARP-149?focusedCommentId=104720
see the first adoption: https://github.com/axonivy/expressive-schema-module?tab=coc-ov-file
=> MARP-149 use a common code-of-conduct throughout the axonivy-org

github-repo-manager/src/main/java/com/axonivy/github/file/GitHubMissingFiles.java
=> No longer check axonivy-market for missing CODE of CONDUCT files

github-repo-manager/src/main/java/com/axonivy/github/GitHubRepos.java
Add vscode-extensions repository to the list of
repositories where the logs are scanned for issues
=> XIVY-15295 Add vscode-extensions to scan issues from

build/raise-ivy-projects-version/raise.sh
automates migrations in integration-tests of the project-build-plugin
https://jenkins.ivyteam.io/job/github-repo-manager_raise-ivy-projects-version/job/raise-plugin/2/console
=> XIVY-15527 auto-raise project-build-plugin integration test projects

build/raiseRepo.sh, build/replace/Jenkinsfile
now I automatically get all my PRs created by a SED run :relaxed: 
see https://jenkins.ivyteam.io/view/scrum-master/job/github-repo-manager_replace/job/personal/4/console
=> auto-assign PRs to user that ran the build :point_right: :person_curly_hair: 

build/raise-build-plugin-version/raise.sh
Skif if raise-build-plugin-version.sh does not exist
=> Fix raise-build-plugin-version
